version: '2.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    container_name: elasticsearch_652
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - ../elk:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    cap_add:
      - IPC_LOCK
    healthcheck:
        test: ["CMD", "curl", "-f", "http://127.0.0.1:9200/_cluster/health"]
        interval: 30s
        timeout: 10s
        retries: 5
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.2
    container_name: kibana_652
    environment:
      - SERVER_HOST=0.0.0.0
    ports:
      - 5601:5601
  lazy-wow-stats:
    image: lazy-wow-stats:1.0
    container_name: lazy_wow_stats
    environment:
      - region=eu
      - eshosts=elasticsearch:9200
      - guilds=guild:realm
      - clientid=Client id from WoW API
      - clientsecret=Client secret from WoW API
    command: node app.js
    depends_on:
      elasticsearch:
        condition: service_healthy
volumes:
  esdata:
    driver: local